### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by mlotysz** [wp2/patronage-17java#5]
* Use default code formatter. We like, when our code is compatible with sun/oracle code conventions.
* Remove useless comments (code should be self documented), see: https://improvingsoftware.com/2011/06/27/5-best-practices-for-commenting-your-code/
* Remove `System.out`, commented out code

**Comment by wp2** [comment]
I try to follow Oracle java naming convention there might be still some variable with incorrect convention but it just easy to miss one
