### ISSUE TITLE
DAO implementation is too complex

### ISSUE THREAD

**Issue by mlotysz** [wp2/patronage-17java#6]
* much of DAO code is repetition and violates DRY principle
* building SQL by concatenating string is error prone and should be avoided
* exception handling is copy pasted in all methods - should be in one place

You could try to familiarize with JPA and CrudRepository (spring-data) interface: http://docs.spring.io/spring-data/data-commons/docs/current/api/org/springframework/data/repository/CrudRepository.html

**Comment by wp2** [comment]
+Jpa Implementation fixed problem of too DAO code (contains only DB operation methods)
+Somtimes i use SQL Query method but i no longer concatenate string
+ Execption handling is no longer copy/paste it is now managed by Exception Advice
